### ISSUE TITLE
Add milliseconds to time picker 

### ISSUE THREAD

**Issue by allanbradl** [masterchief4240/MouseClicker#1]
Great tool, however, could you please add milliseconds to time picker such as HH.MM.SS.fffff ? This would be really nice.

**Comment by masterchief4240** [comment]
Hi, thanks for the feedback. I will look into it and get back to you soon.

**Comment by masterchief4240** [comment]
Sadly, I not able to implement this feature without a lot of extra work, since the DateTimePicker doesn't support milliseconds.

**Comment by masterchief4240** [comment]
Sadly, I am not able to implement this feature without a lot of extra work, since the DateTimePicker doesn't support milliseconds.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datetimepicker.customformat?view=net-5.0

Apparently, the windows system clock only updates every 10-15 milliseconds which makes it impossible to get an accurate value for comparison.

**Comment by allanbradl** [comment]
Hello there !  Thank you very much for looking at my requests !! 
 It is quite incredible that you did ! The real time trigger is a very nice feature,  I will figure something out .  Just for kicks : date time UTC now does the required resolution . 
Never the less , thank you for looking at my requests !
